name: Unit tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4

      - name: Unit tests
        run: ./gradlew :app:testDebugUnitTest --daemon
        env:
          GRADLE_OPTS: "-Xmx3g -Xms256m -XX:MaxMetaspaceSize=512m"

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: |
            app/build/reports/tests/testDebugUnitTest
            app/build/test-results/testDebugUnitTest
